version: '3.2'
services:
  shop:
    image: 92840/shop:dev
    networks:
    - shop
    ports:
    - 8080:8080
    environment:
    - DB.URL=jdbc:h2:tcp://htwo/~/ecommerce
    - DB.USER=adam
    - DB.PASSWORD=adam123
    hostname:
     htwo
    depends_on:
    - htwo
  htwo:
    image: buildo/h2database
    networks:
    - shop
    environment:
    - DRIVERCLASSNAME=org.h2.Driver
    - URL=jdbc:h2:tcp://localhost/~/ecommerce
    - USERNAME=adam
    - PASSWORD=adam123
    volumes:
    - shop:/h2-data

volumes:
  shop:
    driver: local
networks:
  shop:
    driver: bridge