version: '3.2'
services:
  shop:
    image: 92840/shop:dev
    networks:
    - shop
    ports:
    - 8080:8080
    environment:
    - db.url=jdbc:h2:tcp://htwo/~/ecommerce
    - db.user=sa
    - db.password=''
    - db.hostname=htwo
    depends_on:
    - htwo
  htwo:
    image: buildo/h2database
    networks:
    - shop
    environment:
    - driverClassName=org.h2.Driver
    - url=jdbc:h2:tcp://shop/~/ecommerce
    - username=sa
    - password=''
    volumes:
    - shop:/h2-data

volumes:
  shop:
    driver: local
networks:
  shop:
    driver: bridge